//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralPlaceType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="GeneralPlaceType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <choice>
 *         <element name="StructuredPlace" type="{http://bsi.bund.de/eID/}PlaceType"/>
 *         <element name="FreetextPlace" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         <element name="NoPlaceInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       </choice>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralPlaceType", propOrder = {
    "structuredPlace",
    "freetextPlace",
    "noPlaceInfo"
})
public class GeneralPlaceType {

    @XmlElement(name = "StructuredPlace")
    protected PlaceType structuredPlace;
    @XmlElement(name = "FreetextPlace")
    protected String freetextPlace;
    @XmlElement(name = "NoPlaceInfo")
    protected String noPlaceInfo;

    /**
     * Gets the value of the structuredPlace property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceType }
     *     
     */
    public PlaceType getStructuredPlace() {
        return structuredPlace;
    }

    /**
     * Sets the value of the structuredPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceType }
     *     
     */
    public void setStructuredPlace(PlaceType value) {
        this.structuredPlace = value;
    }

    /**
     * Gets the value of the freetextPlace property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreetextPlace() {
        return freetextPlace;
    }

    /**
     * Sets the value of the freetextPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreetextPlace(String value) {
        this.freetextPlace = value;
    }

    /**
     * Gets the value of the noPlaceInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoPlaceInfo() {
        return noPlaceInfo;
    }

    /**
     * Sets the value of the noPlaceInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoPlaceInfo(String value) {
        this.noPlaceInfo = value;
    }

}
