//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getServerInfoResponseType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="getServerInfoResponseType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="ServerVersion" type="{http://bsi.bund.de/eID/}VersionType"/>
 *         <element name="DocumentVerificationRights" type="{http://bsi.bund.de/eID/}OperationsSelectorType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getServerInfoResponseType", propOrder = {
    "serverVersion",
    "documentVerificationRights"
})
public class GetServerInfoResponseType {

    @XmlElement(name = "ServerVersion", required = true)
    protected VersionType serverVersion;
    @XmlElement(name = "DocumentVerificationRights", required = true)
    protected OperationsSelectorType documentVerificationRights;

    /**
     * Gets the value of the serverVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionType }
     *     
     */
    public VersionType getServerVersion() {
        return serverVersion;
    }

    /**
     * Sets the value of the serverVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionType }
     *     
     */
    public void setServerVersion(VersionType value) {
        this.serverVersion = value;
    }

    /**
     * Gets the value of the documentVerificationRights property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsSelectorType }
     *     
     */
    public OperationsSelectorType getDocumentVerificationRights() {
        return documentVerificationRights;
    }

    /**
     * Sets the value of the documentVerificationRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsSelectorType }
     *     
     */
    public void setDocumentVerificationRights(OperationsSelectorType value) {
        this.documentVerificationRights = value;
    }

}
