//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import oasis.names.tc.saml._2_0.assertion.EncryptedElementType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.bund.bsi.eid package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _UseIDResponse_QNAME = new QName("http://bsi.bund.de/eID/", "useIDResponse");
    private static final QName _UseIDRequest_QNAME = new QName("http://bsi.bund.de/eID/", "useIDRequest");
    private static final QName _GetServerInfoResponse_QNAME = new QName("http://bsi.bund.de/eID/", "getServerInfoResponse");
    private static final QName _GetServerInfoRequest_QNAME = new QName("http://bsi.bund.de/eID/", "getServerInfoRequest");
    private static final QName _GetResultRequest_QNAME = new QName("http://bsi.bund.de/eID/", "getResultRequest");
    private static final QName _GetResultResponse_QNAME = new QName("http://bsi.bund.de/eID/", "getResultResponse");
    private static final QName _EncryptedAuthnRequestExtension_QNAME = new QName("http://bsi.bund.de/eID/", "EncryptedAuthnRequestExtension");
    private static final QName _AuthnRequestExtension_QNAME = new QName("http://bsi.bund.de/eID/", "AuthnRequestExtension");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.bund.bsi.eid
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UseIDResponseType }
     * 
     * @return
     *     the new instance of {@link UseIDResponseType }
     */
    public UseIDResponseType createUseIDResponseType() {
        return new UseIDResponseType();
    }

    /**
     * Create an instance of {@link UseIDRequestType }
     * 
     * @return
     *     the new instance of {@link UseIDRequestType }
     */
    public UseIDRequestType createUseIDRequestType() {
        return new UseIDRequestType();
    }

    /**
     * Create an instance of {@link GetServerInfoResponseType }
     * 
     * @return
     *     the new instance of {@link GetServerInfoResponseType }
     */
    public GetServerInfoResponseType createGetServerInfoResponseType() {
        return new GetServerInfoResponseType();
    }

    /**
     * Create an instance of {@link NullType }
     * 
     * @return
     *     the new instance of {@link NullType }
     */
    public NullType createNullType() {
        return new NullType();
    }

    /**
     * Create an instance of {@link GetResultRequestType }
     * 
     * @return
     *     the new instance of {@link GetResultRequestType }
     */
    public GetResultRequestType createGetResultRequestType() {
        return new GetResultRequestType();
    }

    /**
     * Create an instance of {@link GetResultResponseType }
     * 
     * @return
     *     the new instance of {@link GetResultResponseType }
     */
    public GetResultResponseType createGetResultResponseType() {
        return new GetResultResponseType();
    }

    /**
     * Create an instance of {@link AuthnRequestExtensionType }
     * 
     * @return
     *     the new instance of {@link AuthnRequestExtensionType }
     */
    public AuthnRequestExtensionType createAuthnRequestExtensionType() {
        return new AuthnRequestExtensionType();
    }

    /**
     * Create an instance of {@link SessionType }
     * 
     * @return
     *     the new instance of {@link SessionType }
     */
    public SessionType createSessionType() {
        return new SessionType();
    }

    /**
     * Create an instance of {@link PersonalDataType }
     * 
     * @return
     *     the new instance of {@link PersonalDataType }
     */
    public PersonalDataType createPersonalDataType() {
        return new PersonalDataType();
    }

    /**
     * Create an instance of {@link GeneralPlaceType }
     * 
     * @return
     *     the new instance of {@link GeneralPlaceType }
     */
    public GeneralPlaceType createGeneralPlaceType() {
        return new GeneralPlaceType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     * @return
     *     the new instance of {@link PlaceType }
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link AgeVerificationRequestType }
     * 
     * @return
     *     the new instance of {@link AgeVerificationRequestType }
     */
    public AgeVerificationRequestType createAgeVerificationRequestType() {
        return new AgeVerificationRequestType();
    }

    /**
     * Create an instance of {@link VerificationResultType }
     * 
     * @return
     *     the new instance of {@link VerificationResultType }
     */
    public VerificationResultType createVerificationResultType() {
        return new VerificationResultType();
    }

    /**
     * Create an instance of {@link OperationsSelectorType }
     * 
     * @return
     *     the new instance of {@link OperationsSelectorType }
     */
    public OperationsSelectorType createOperationsSelectorType() {
        return new OperationsSelectorType();
    }

    /**
     * Create an instance of {@link PlaceVerificationRequestType }
     * 
     * @return
     *     the new instance of {@link PlaceVerificationRequestType }
     */
    public PlaceVerificationRequestType createPlaceVerificationRequestType() {
        return new PlaceVerificationRequestType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     * @return
     *     the new instance of {@link VersionType }
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link PreSharedKeyType }
     * 
     * @return
     *     the new instance of {@link PreSharedKeyType }
     */
    public PreSharedKeyType createPreSharedKeyType() {
        return new PreSharedKeyType();
    }

    /**
     * Create an instance of {@link GeneralDateType }
     * 
     * @return
     *     the new instance of {@link GeneralDateType }
     */
    public GeneralDateType createGeneralDateType() {
        return new GeneralDateType();
    }

    /**
     * Create an instance of {@link RestrictedIDType }
     * 
     * @return
     *     the new instance of {@link RestrictedIDType }
     */
    public RestrictedIDType createRestrictedIDType() {
        return new RestrictedIDType();
    }

    /**
     * Create an instance of {@link PlaceVerificationResultType }
     * 
     * @return
     *     the new instance of {@link PlaceVerificationResultType }
     */
    public PlaceVerificationResultType createPlaceVerificationResultType() {
        return new PlaceVerificationResultType();
    }

    /**
     * Create an instance of {@link AgeVerificationResultType }
     * 
     * @return
     *     the new instance of {@link AgeVerificationResultType }
     */
    public AgeVerificationResultType createAgeVerificationResultType() {
        return new AgeVerificationResultType();
    }

    /**
     * Create an instance of {@link DocumentValidityResultType }
     * 
     * @return
     *     the new instance of {@link DocumentValidityResultType }
     */
    public DocumentValidityResultType createDocumentValidityResultType() {
        return new DocumentValidityResultType();
    }

    /**
     * Create an instance of {@link RequestedAttributesType }
     * 
     * @return
     *     the new instance of {@link RequestedAttributesType }
     */
    public RequestedAttributesType createRequestedAttributesType() {
        return new RequestedAttributesType();
    }

    /**
     * Create an instance of {@link OperationsRequestorType }
     * 
     * @return
     *     the new instance of {@link OperationsRequestorType }
     */
    public OperationsRequestorType createOperationsRequestorType() {
        return new OperationsRequestorType();
    }

    /**
     * Create an instance of {@link OperationsResponderType }
     * 
     * @return
     *     the new instance of {@link OperationsResponderType }
     */
    public OperationsResponderType createOperationsResponderType() {
        return new OperationsResponderType();
    }

    /**
     * Create an instance of {@link EidasExtensionType }
     * 
     * @return
     *     the new instance of {@link EidasExtensionType }
     */
    public EidasExtensionType createEidasExtensionType() {
        return new EidasExtensionType();
    }

    /**
     * Create an instance of {@link TransactionAttestationRequestType }
     * 
     * @return
     *     the new instance of {@link TransactionAttestationRequestType }
     */
    public TransactionAttestationRequestType createTransactionAttestationRequestType() {
        return new TransactionAttestationRequestType();
    }

    /**
     * Create an instance of {@link TransactionAttestationResponseType }
     * 
     * @return
     *     the new instance of {@link TransactionAttestationResponseType }
     */
    public TransactionAttestationResponseType createTransactionAttestationResponseType() {
        return new TransactionAttestationResponseType();
    }

    /**
     * Create an instance of {@link EIDTypeRequestType }
     * 
     * @return
     *     the new instance of {@link EIDTypeRequestType }
     */
    public EIDTypeRequestType createEIDTypeRequestType() {
        return new EIDTypeRequestType();
    }

    /**
     * Create an instance of {@link EIDTypeResponseType }
     * 
     * @return
     *     the new instance of {@link EIDTypeResponseType }
     */
    public EIDTypeResponseType createEIDTypeResponseType() {
        return new EIDTypeResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseIDResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UseIDResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "useIDResponse")
    public JAXBElement<UseIDResponseType> createUseIDResponse(UseIDResponseType value) {
        return new JAXBElement<>(_UseIDResponse_QNAME, UseIDResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UseIDRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UseIDRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "useIDRequest")
    public JAXBElement<UseIDRequestType> createUseIDRequest(UseIDRequestType value) {
        return new JAXBElement<>(_UseIDRequest_QNAME, UseIDRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServerInfoResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetServerInfoResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "getServerInfoResponse")
    public JAXBElement<GetServerInfoResponseType> createGetServerInfoResponse(GetServerInfoResponseType value) {
        return new JAXBElement<>(_GetServerInfoResponse_QNAME, GetServerInfoResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NullType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link NullType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "getServerInfoRequest")
    public JAXBElement<NullType> createGetServerInfoRequest(NullType value) {
        return new JAXBElement<>(_GetServerInfoRequest_QNAME, NullType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetResultRequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetResultRequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "getResultRequest")
    public JAXBElement<GetResultRequestType> createGetResultRequest(GetResultRequestType value) {
        return new JAXBElement<>(_GetResultRequest_QNAME, GetResultRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetResultResponseType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetResultResponseType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "getResultResponse")
    public JAXBElement<GetResultResponseType> createGetResultResponse(GetResultResponseType value) {
        return new JAXBElement<>(_GetResultResponse_QNAME, GetResultResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EncryptedElementType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link EncryptedElementType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "EncryptedAuthnRequestExtension")
    public JAXBElement<EncryptedElementType> createEncryptedAuthnRequestExtension(EncryptedElementType value) {
        return new JAXBElement<>(_EncryptedAuthnRequestExtension_QNAME, EncryptedElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthnRequestExtensionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AuthnRequestExtensionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://bsi.bund.de/eID/", name = "AuthnRequestExtension")
    public JAXBElement<AuthnRequestExtensionType> createAuthnRequestExtension(AuthnRequestExtensionType value) {
        return new JAXBElement<>(_AuthnRequestExtension_QNAME, AuthnRequestExtensionType.class, null, value);
    }

}
