//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationsResponderType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="OperationsResponderType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="DocumentType" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="IssuingState" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="DateOfExpiry" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="GivenNames" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="FamilyNames" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="ArtisticName" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="AcademicTitle" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="DateOfBirth" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="PlaceOfBirth" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="Nationality" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="BirthName" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="PlaceOfResidence" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="CommunityID" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="ResidencePermitI" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="RestrictedID" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="AgeVerification" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *         <element name="PlaceVerification" type="{http://bsi.bund.de/eID/}AttributeResponseType"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationsResponderType", propOrder = {
    "documentType",
    "issuingState",
    "dateOfExpiry",
    "givenNames",
    "familyNames",
    "artisticName",
    "academicTitle",
    "dateOfBirth",
    "placeOfBirth",
    "nationality",
    "birthName",
    "placeOfResidence",
    "communityID",
    "residencePermitI",
    "restrictedID",
    "ageVerification",
    "placeVerification"
})
public class OperationsResponderType {

    @XmlElement(name = "DocumentType", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType documentType;
    @XmlElement(name = "IssuingState", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType issuingState;
    @XmlElement(name = "DateOfExpiry", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType dateOfExpiry;
    @XmlElement(name = "GivenNames", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType givenNames;
    @XmlElement(name = "FamilyNames", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType familyNames;
    @XmlElement(name = "ArtisticName", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType artisticName;
    @XmlElement(name = "AcademicTitle", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType academicTitle;
    @XmlElement(name = "DateOfBirth", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType dateOfBirth;
    @XmlElement(name = "PlaceOfBirth", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType placeOfBirth;
    @XmlElement(name = "Nationality", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType nationality;
    @XmlElement(name = "BirthName", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType birthName;
    @XmlElement(name = "PlaceOfResidence", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType placeOfResidence;
    @XmlElement(name = "CommunityID", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType communityID;
    @XmlElement(name = "ResidencePermitI", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType residencePermitI;
    @XmlElement(name = "RestrictedID", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType restrictedID;
    @XmlElement(name = "AgeVerification", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType ageVerification;
    @XmlElement(name = "PlaceVerification", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeResponseType placeVerification;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setDocumentType(AttributeResponseType value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the issuingState property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getIssuingState() {
        return issuingState;
    }

    /**
     * Sets the value of the issuingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setIssuingState(AttributeResponseType value) {
        this.issuingState = value;
    }

    /**
     * Gets the value of the dateOfExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getDateOfExpiry() {
        return dateOfExpiry;
    }

    /**
     * Sets the value of the dateOfExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setDateOfExpiry(AttributeResponseType value) {
        this.dateOfExpiry = value;
    }

    /**
     * Gets the value of the givenNames property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getGivenNames() {
        return givenNames;
    }

    /**
     * Sets the value of the givenNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setGivenNames(AttributeResponseType value) {
        this.givenNames = value;
    }

    /**
     * Gets the value of the familyNames property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getFamilyNames() {
        return familyNames;
    }

    /**
     * Sets the value of the familyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setFamilyNames(AttributeResponseType value) {
        this.familyNames = value;
    }

    /**
     * Gets the value of the artisticName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getArtisticName() {
        return artisticName;
    }

    /**
     * Sets the value of the artisticName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setArtisticName(AttributeResponseType value) {
        this.artisticName = value;
    }

    /**
     * Gets the value of the academicTitle property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getAcademicTitle() {
        return academicTitle;
    }

    /**
     * Sets the value of the academicTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setAcademicTitle(AttributeResponseType value) {
        this.academicTitle = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setDateOfBirth(AttributeResponseType value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setPlaceOfBirth(AttributeResponseType value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setNationality(AttributeResponseType value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getBirthName() {
        return birthName;
    }

    /**
     * Sets the value of the birthName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setBirthName(AttributeResponseType value) {
        this.birthName = value;
    }

    /**
     * Gets the value of the placeOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getPlaceOfResidence() {
        return placeOfResidence;
    }

    /**
     * Sets the value of the placeOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setPlaceOfResidence(AttributeResponseType value) {
        this.placeOfResidence = value;
    }

    /**
     * Gets the value of the communityID property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getCommunityID() {
        return communityID;
    }

    /**
     * Sets the value of the communityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setCommunityID(AttributeResponseType value) {
        this.communityID = value;
    }

    /**
     * Gets the value of the residencePermitI property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getResidencePermitI() {
        return residencePermitI;
    }

    /**
     * Sets the value of the residencePermitI property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setResidencePermitI(AttributeResponseType value) {
        this.residencePermitI = value;
    }

    /**
     * Gets the value of the restrictedID property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getRestrictedID() {
        return restrictedID;
    }

    /**
     * Sets the value of the restrictedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setRestrictedID(AttributeResponseType value) {
        this.restrictedID = value;
    }

    /**
     * Gets the value of the ageVerification property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getAgeVerification() {
        return ageVerification;
    }

    /**
     * Sets the value of the ageVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setAgeVerification(AttributeResponseType value) {
        this.ageVerification = value;
    }

    /**
     * Gets the value of the placeVerification property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeResponseType }
     *     
     */
    public AttributeResponseType getPlaceVerification() {
        return placeVerification;
    }

    /**
     * Sets the value of the placeVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeResponseType }
     *     
     */
    public void setPlaceVerification(AttributeResponseType value) {
        this.placeVerification = value;
    }

}
