//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for useIDRequestType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="useIDRequestType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="UseOperations" type="{http://bsi.bund.de/eID/}OperationsRequestorType"/>
 *         <element name="AgeVerificationRequest" type="{http://bsi.bund.de/eID/}AgeVerificationRequestType" minOccurs="0"/>
 *         <element name="PlaceVerificationRequest" type="{http://bsi.bund.de/eID/}PlaceVerificationRequestType" minOccurs="0"/>
 *         <element name="TransactionInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         <element name="TransactionAttestationRequest" type="{http://bsi.bund.de/eID/}TransactionAttestationRequestType" minOccurs="0"/>
 *         <element name="LevelOfAssuranceRequest" type="{http://bsi.bund.de/eID/}LevelOfAssuranceType" minOccurs="0"/>
 *         <element name="EIDTypeRequest" type="{http://bsi.bund.de/eID/}EIDTypeRequestType" minOccurs="0"/>
 *         <element name="PSK" type="{http://bsi.bund.de/eID/}PreSharedKeyType" minOccurs="0"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "useIDRequestType", propOrder = {
    "useOperations",
    "ageVerificationRequest",
    "placeVerificationRequest",
    "transactionInfo",
    "transactionAttestationRequest",
    "levelOfAssuranceRequest",
    "eidTypeRequest",
    "psk"
})
public class UseIDRequestType {

    @XmlElement(name = "UseOperations", required = true)
    protected OperationsRequestorType useOperations;
    @XmlElement(name = "AgeVerificationRequest")
    protected AgeVerificationRequestType ageVerificationRequest;
    @XmlElement(name = "PlaceVerificationRequest")
    protected PlaceVerificationRequestType placeVerificationRequest;
    @XmlElement(name = "TransactionInfo")
    protected String transactionInfo;
    @XmlElement(name = "TransactionAttestationRequest")
    protected TransactionAttestationRequestType transactionAttestationRequest;
    @XmlElement(name = "LevelOfAssuranceRequest")
    @XmlSchemaType(name = "anyURI")
    protected String levelOfAssuranceRequest;
    @XmlElement(name = "EIDTypeRequest")
    protected EIDTypeRequestType eidTypeRequest;
    @XmlElement(name = "PSK")
    protected PreSharedKeyType psk;

    /**
     * Gets the value of the useOperations property.
     * 
     * @return
     *     possible object is
     *     {@link OperationsRequestorType }
     *     
     */
    public OperationsRequestorType getUseOperations() {
        return useOperations;
    }

    /**
     * Sets the value of the useOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationsRequestorType }
     *     
     */
    public void setUseOperations(OperationsRequestorType value) {
        this.useOperations = value;
    }

    /**
     * Gets the value of the ageVerificationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AgeVerificationRequestType }
     *     
     */
    public AgeVerificationRequestType getAgeVerificationRequest() {
        return ageVerificationRequest;
    }

    /**
     * Sets the value of the ageVerificationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgeVerificationRequestType }
     *     
     */
    public void setAgeVerificationRequest(AgeVerificationRequestType value) {
        this.ageVerificationRequest = value;
    }

    /**
     * Gets the value of the placeVerificationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceVerificationRequestType }
     *     
     */
    public PlaceVerificationRequestType getPlaceVerificationRequest() {
        return placeVerificationRequest;
    }

    /**
     * Sets the value of the placeVerificationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceVerificationRequestType }
     *     
     */
    public void setPlaceVerificationRequest(PlaceVerificationRequestType value) {
        this.placeVerificationRequest = value;
    }

    /**
     * Gets the value of the transactionInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionInfo() {
        return transactionInfo;
    }

    /**
     * Sets the value of the transactionInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionInfo(String value) {
        this.transactionInfo = value;
    }

    /**
     * Gets the value of the transactionAttestationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionAttestationRequestType }
     *     
     */
    public TransactionAttestationRequestType getTransactionAttestationRequest() {
        return transactionAttestationRequest;
    }

    /**
     * Sets the value of the transactionAttestationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionAttestationRequestType }
     *     
     */
    public void setTransactionAttestationRequest(TransactionAttestationRequestType value) {
        this.transactionAttestationRequest = value;
    }

    /**
     * Gets the value of the levelOfAssuranceRequest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelOfAssuranceRequest() {
        return levelOfAssuranceRequest;
    }

    /**
     * Sets the value of the levelOfAssuranceRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelOfAssuranceRequest(String value) {
        this.levelOfAssuranceRequest = value;
    }

    /**
     * Gets the value of the eidTypeRequest property.
     * 
     * @return
     *     possible object is
     *     {@link EIDTypeRequestType }
     *     
     */
    public EIDTypeRequestType getEIDTypeRequest() {
        return eidTypeRequest;
    }

    /**
     * Sets the value of the eidTypeRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link EIDTypeRequestType }
     *     
     */
    public void setEIDTypeRequest(EIDTypeRequestType value) {
        this.eidTypeRequest = value;
    }

    /**
     * Gets the value of the psk property.
     * 
     * @return
     *     possible object is
     *     {@link PreSharedKeyType }
     *     
     */
    public PreSharedKeyType getPSK() {
        return psk;
    }

    /**
     * Sets the value of the psk property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreSharedKeyType }
     *     
     */
    public void setPSK(PreSharedKeyType value) {
        this.psk = value;
    }

}
