//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import oasis.names.tc.dss._1_0.core.schema.Result;


/**
 * <p>Java class for useIDResponseType complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType name="useIDResponseType">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="Session" type="{http://bsi.bund.de/eID/}SessionType"/>
 *         <element name="eCardServerAddress" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         <element name="PSK" type="{http://bsi.bund.de/eID/}PreSharedKeyType"/>
 *         <element ref="{urn:oasis:names:tc:dss:1.0:core:schema}Result"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "useIDResponseType", propOrder = {
    "session",
    "eCardServerAddress",
    "psk",
    "result"
})
public class UseIDResponseType {

    @XmlElement(name = "Session", required = true)
    protected SessionType session;
    @XmlSchemaType(name = "anyURI")
    protected String eCardServerAddress;
    @XmlElement(name = "PSK", required = true)
    protected PreSharedKeyType psk;
    @XmlElement(name = "Result", namespace = "urn:oasis:names:tc:dss:1.0:core:schema", required = true)
    protected Result result;

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link SessionType }
     *     
     */
    public SessionType getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionType }
     *     
     */
    public void setSession(SessionType value) {
        this.session = value;
    }

    /**
     * Gets the value of the eCardServerAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECardServerAddress() {
        return eCardServerAddress;
    }

    /**
     * Sets the value of the eCardServerAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECardServerAddress(String value) {
        this.eCardServerAddress = value;
    }

    /**
     * Gets the value of the psk property.
     * 
     * @return
     *     possible object is
     *     {@link PreSharedKeyType }
     *     
     */
    public PreSharedKeyType getPSK() {
        return psk;
    }

    /**
     * Sets the value of the psk property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreSharedKeyType }
     *     
     */
    public void setPSK(PreSharedKeyType value) {
        this.psk = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Result }
     *     
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Result }
     *     
     */
    public void setResult(Result value) {
        this.result = value;
    }

}
