//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//


package wsdl.de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EidasExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EidasExtensionType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LevelOfAssurance" type="{http://bsi.bund.de/eID/}LevelOfAssuranceType" minOccurs="0"/&gt;
 *         &lt;element name="SendingMemberState" type="{http://bsi.bund.de/eID/}SendingMemberStateType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EidasExtensionType", propOrder = {
    "levelOfAssurance",
    "sendingMemberState"
})
public class EidasExtensionType {

    @XmlElement(name = "LevelOfAssurance", defaultValue = "http://eidas.europa.eu/LoA/high")
    @XmlSchemaType(name = "anyURI")
    protected String levelOfAssurance;
    @XmlElement(name = "SendingMemberState")
    protected String sendingMemberState;

    /**
     * Gets the value of the levelOfAssurance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevelOfAssurance() {
        return levelOfAssurance;
    }

    /**
     * Sets the value of the levelOfAssurance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevelOfAssurance(String value) {
        this.levelOfAssurance = value;
    }

    /**
     * Gets the value of the sendingMemberState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSendingMemberState() {
        return sendingMemberState;
    }

    /**
     * Sets the value of the sendingMemberState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSendingMemberState(String value) {
        this.sendingMemberState = value;
    }

}
