//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//


package wsdl.de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentityFlavourType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="IdentityFlavourType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NaturalPerson"/&gt;
 *     &lt;enumeration value="LegalPerson"/&gt;
 *     &lt;enumeration value="LegalPersonRepresentative"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "IdentityFlavourType")
@XmlEnum
public enum IdentityFlavourType {

    @XmlEnumValue("NaturalPerson")
    NATURAL_PERSON("NaturalPerson"),
    @XmlEnumValue("LegalPerson")
    LEGAL_PERSON("LegalPerson"),
    @XmlEnumValue("LegalPersonRepresentative")
    LEGAL_PERSON_REPRESENTATIVE("LegalPersonRepresentative");
    private final String value;

    IdentityFlavourType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdentityFlavourType fromValue(String v) {
        for (IdentityFlavourType c: IdentityFlavourType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
