//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//


package wsdl.de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationsSelectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationsSelectorType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="DocumentType" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="IssuingState" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="DateOfExpiry" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="GivenNames" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="FamilyNames" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="ArtisticName" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="AcademicTitle" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="DateOfBirth" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="PlaceOfBirth" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="Nationality" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="BirthName" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="PlaceOfResidence" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="CommunityID" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="ResidencePermitI" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="RestrictedID" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="AgeVerification" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *         &lt;element name="PlaceVerification" type="{http://bsi.bund.de/eID/}AttributeSelectionType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationsSelectorType", propOrder = {
    "documentType",
    "issuingState",
    "dateOfExpiry",
    "givenNames",
    "familyNames",
    "artisticName",
    "academicTitle",
    "dateOfBirth",
    "placeOfBirth",
    "nationality",
    "birthName",
    "placeOfResidence",
    "communityID",
    "residencePermitI",
    "restrictedID",
    "ageVerification",
    "placeVerification"
})
public class OperationsSelectorType {

    @XmlElement(name = "DocumentType", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType documentType;
    @XmlElement(name = "IssuingState", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType issuingState;
    @XmlElement(name = "DateOfExpiry", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType dateOfExpiry;
    @XmlElement(name = "GivenNames", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType givenNames;
    @XmlElement(name = "FamilyNames", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType familyNames;
    @XmlElement(name = "ArtisticName", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType artisticName;
    @XmlElement(name = "AcademicTitle", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType academicTitle;
    @XmlElement(name = "DateOfBirth", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType dateOfBirth;
    @XmlElement(name = "PlaceOfBirth", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType placeOfBirth;
    @XmlElement(name = "Nationality", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType nationality;
    @XmlElement(name = "BirthName", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType birthName;
    @XmlElement(name = "PlaceOfResidence", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType placeOfResidence;
    @XmlElement(name = "CommunityID", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType communityID;
    @XmlElement(name = "ResidencePermitI", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType residencePermitI;
    @XmlElement(name = "RestrictedID", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType restrictedID;
    @XmlElement(name = "AgeVerification", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType ageVerification;
    @XmlElement(name = "PlaceVerification", required = true, defaultValue = "PROHIBITED")
    @XmlSchemaType(name = "string")
    protected AttributeSelectionType placeVerification;

    /**
     * Gets the value of the documentType property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setDocumentType(AttributeSelectionType value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the issuingState property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getIssuingState() {
        return issuingState;
    }

    /**
     * Sets the value of the issuingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setIssuingState(AttributeSelectionType value) {
        this.issuingState = value;
    }

    /**
     * Gets the value of the dateOfExpiry property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getDateOfExpiry() {
        return dateOfExpiry;
    }

    /**
     * Sets the value of the dateOfExpiry property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setDateOfExpiry(AttributeSelectionType value) {
        this.dateOfExpiry = value;
    }

    /**
     * Gets the value of the givenNames property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getGivenNames() {
        return givenNames;
    }

    /**
     * Sets the value of the givenNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setGivenNames(AttributeSelectionType value) {
        this.givenNames = value;
    }

    /**
     * Gets the value of the familyNames property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getFamilyNames() {
        return familyNames;
    }

    /**
     * Sets the value of the familyNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setFamilyNames(AttributeSelectionType value) {
        this.familyNames = value;
    }

    /**
     * Gets the value of the artisticName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getArtisticName() {
        return artisticName;
    }

    /**
     * Sets the value of the artisticName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setArtisticName(AttributeSelectionType value) {
        this.artisticName = value;
    }

    /**
     * Gets the value of the academicTitle property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getAcademicTitle() {
        return academicTitle;
    }

    /**
     * Sets the value of the academicTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setAcademicTitle(AttributeSelectionType value) {
        this.academicTitle = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setDateOfBirth(AttributeSelectionType value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the placeOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * Sets the value of the placeOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setPlaceOfBirth(AttributeSelectionType value) {
        this.placeOfBirth = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setNationality(AttributeSelectionType value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthName property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getBirthName() {
        return birthName;
    }

    /**
     * Sets the value of the birthName property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setBirthName(AttributeSelectionType value) {
        this.birthName = value;
    }

    /**
     * Gets the value of the placeOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getPlaceOfResidence() {
        return placeOfResidence;
    }

    /**
     * Sets the value of the placeOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setPlaceOfResidence(AttributeSelectionType value) {
        this.placeOfResidence = value;
    }

    /**
     * Gets the value of the communityID property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getCommunityID() {
        return communityID;
    }

    /**
     * Sets the value of the communityID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setCommunityID(AttributeSelectionType value) {
        this.communityID = value;
    }

    /**
     * Gets the value of the residencePermitI property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getResidencePermitI() {
        return residencePermitI;
    }

    /**
     * Sets the value of the residencePermitI property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setResidencePermitI(AttributeSelectionType value) {
        this.residencePermitI = value;
    }

    /**
     * Gets the value of the restrictedID property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getRestrictedID() {
        return restrictedID;
    }

    /**
     * Sets the value of the restrictedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setRestrictedID(AttributeSelectionType value) {
        this.restrictedID = value;
    }

    /**
     * Gets the value of the ageVerification property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getAgeVerification() {
        return ageVerification;
    }

    /**
     * Sets the value of the ageVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setAgeVerification(AttributeSelectionType value) {
        this.ageVerification = value;
    }

    /**
     * Gets the value of the placeVerification property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeSelectionType }
     *     
     */
    public AttributeSelectionType getPlaceVerification() {
        return placeVerification;
    }

    /**
     * Sets the value of the placeVerification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeSelectionType }
     *     
     */
    public void setPlaceVerification(AttributeSelectionType value) {
        this.placeVerification = value;
    }

}
