//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//


package wsdl.de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlaceVerificationResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PlaceVerificationResultType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Request" type="{http://bsi.bund.de/eID/}PlaceVerificationRequestType"/&gt;
 *         &lt;element name="Result" type="{http://bsi.bund.de/eID/}VerificationResultType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PlaceVerificationResultType", propOrder = {
    "request",
    "result"
})
public class PlaceVerificationResultType {

    @XmlElement(name = "Request", required = true)
    protected PlaceVerificationRequestType request;
    @XmlElement(name = "Result", required = true)
    protected VerificationResultType result;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link PlaceVerificationRequestType }
     *     
     */
    public PlaceVerificationRequestType getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlaceVerificationRequestType }
     *     
     */
    public void setRequest(PlaceVerificationRequestType value) {
        this.request = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationResultType }
     *     
     */
    public VerificationResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationResultType }
     *     
     */
    public void setResult(VerificationResultType value) {
        this.result = value;
    }

}
