//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//


package wsdl.de.bund.bsi.eid;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import wsdl.oasis.names.tc.dss._1_0.core.schema.AnyType;


/**
 * <p>Java class for TransactionAttestationResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionAttestationResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionAttestationFormat" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="TransactionAttestationData" type="{urn:oasis:names:tc:dss:1.0:core:schema}AnyType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionAttestationResponseType", propOrder = {
    "transactionAttestationFormat",
    "transactionAttestationData"
})
public class TransactionAttestationResponseType {

    @XmlElement(name = "TransactionAttestationFormat", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String transactionAttestationFormat;
    @XmlElement(name = "TransactionAttestationData", required = true)
    protected AnyType transactionAttestationData;

    /**
     * Gets the value of the transactionAttestationFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionAttestationFormat() {
        return transactionAttestationFormat;
    }

    /**
     * Sets the value of the transactionAttestationFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionAttestationFormat(String value) {
        this.transactionAttestationFormat = value;
    }

    /**
     * Gets the value of the transactionAttestationData property.
     * 
     * @return
     *     possible object is
     *     {@link AnyType }
     *     
     */
    public AnyType getTransactionAttestationData() {
        return transactionAttestationData;
    }

    /**
     * Sets the value of the transactionAttestationData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnyType }
     *     
     */
    public void setTransactionAttestationData(AnyType value) {
        this.transactionAttestationData = value;
    }

}
