apiVersion: apps/v1
kind: Deployment
metadata:
  name: common
  namespace: ausweisapp
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-ausweisapp-common
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: EXECUTOR
          value: "3"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: PASSWORD
              name: android-passwords
              optional: false
        image: dev-docker.governikus.de/ausweisapp2/alpine:common
        imagePullPolicy: Always
        name: common
        resources:
          limits:
            cpu: "3"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 2Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        tty: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
