//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.30 at 11:23:35 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:oasis:names:tc:dss:1.0:core:schema", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package wsdl.oasis.names.tc.dss._1_0.core.schema;
